import Lead from '../models/Lead.js';
import nodemailer from 'nodemailer';

const sendLeadEmail = async (leadData) => {
  try {
    const transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST,
      port: process.env.SMTP_PORT,
      secure: process.env.SMTP_PORT === '465', // true for 465, false for other ports
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS,
      },
    });

    const adminHtml = `
      <div style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e2e8f0; border-radius: 12px; overflow: hidden; background-color: #ffffff;">
        <div style="background-color: #ffffff; border-bottom: 2px solid #2E7D32; padding: 24px; text-align: center;">
          <img src="${process.env.FRONTEND_URL || 'https://steam-core.vercel.app'}/logo.png" alt="SteamCore AI" style="height: 60px; width: auto; margin-bottom: 8px;" />
          <p style="color: #64748b; margin: 0; font-size: 14px; font-weight: 500; text-transform: uppercase; letter-spacing: 1px;">New Lead Generated by AI Chatbot</p>
        </div>
        <div style="padding: 32px;">
          <h2 style="color: #2E7D32; margin-top: 0;">Lead Details</h2>
          <table style="width: 100%; border-collapse: collapse; margin-bottom: 24px;">
            <tr><td style="padding: 10px 0; border-bottom: 1px solid #e2e8f0; color: #64748b; width: 140px;">Name</td><td style="padding: 10px 0; border-bottom: 1px solid #e2e8f0; font-weight: 600; color: #0f172a;">${leadData.fullName}</td></tr>
            <tr><td style="padding: 10px 0; border-bottom: 1px solid #e2e8f0; color: #64748b;">Company</td><td style="padding: 10px 0; border-bottom: 1px solid #e2e8f0; font-weight: 600; color: #0f172a;">${leadData.companyName || 'N/A'}</td></tr>
            <tr><td style="padding: 10px 0; border-bottom: 1px solid #e2e8f0; color: #64748b;">Industry</td><td style="padding: 10px 0; border-bottom: 1px solid #e2e8f0; font-weight: 600; color: #0f172a;">${leadData.industry || 'N/A'}</td></tr>
            <tr><td style="padding: 10px 0; border-bottom: 1px solid #e2e8f0; color: #64748b;">Email</td><td style="padding: 10px 0; border-bottom: 1px solid #e2e8f0; font-weight: 600; color: #0f172a;">${leadData.email}</td></tr>
            <tr><td style="padding: 10px 0; border-bottom: 1px solid #e2e8f0; color: #64748b;">Phone</td><td style="padding: 10px 0; border-bottom: 1px solid #e2e8f0; font-weight: 600; color: #0f172a;">${leadData.phoneNumber}</td></tr>
            <tr><td style="padding: 10px 0; border-bottom: 1px solid #e2e8f0; color: #64748b;">City</td><td style="padding: 10px 0; border-bottom: 1px solid #e2e8f0; font-weight: 600; color: #0f172a;">${leadData.city || 'N/A'}</td></tr>
            <tr><td style="padding: 10px 0; border-bottom: 1px solid #e2e8f0; color: #64748b;">Requirement</td><td style="padding: 10px 0; border-bottom: 1px solid #e2e8f0; font-weight: 600; color: #0f172a;">${leadData.requirement}</td></tr>
            <tr><td style="padding: 10px 0; border-bottom: 1px solid #e2e8f0; color: #64748b;">Budget</td><td style="padding: 10px 0; border-bottom: 1px solid #e2e8f0; font-weight: 600; color: #0f172a;">${leadData.budget || 'N/A'}</td></tr>
            <tr><td style="padding: 10px 0; border-bottom: 1px solid #e2e8f0; color: #64748b;">Preferred Contact</td><td style="padding: 10px 0; border-bottom: 1px solid #e2e8f0; font-weight: 600; color: #0f172a;">${leadData.preferredContactMethod || 'Email'}</td></tr>
          </table>
          <h3 style="color: #2E7D32; margin-bottom: 8px;">Message:</h3>
          <div style="background-color: #f8fafc; padding: 16px; border-radius: 8px; color: #334155; line-height: 1.6; white-space: pre-wrap;">${leadData.message || 'N/A'}</div>
        </div>
      </div>
    `;

    const adminMailOptions = {
      from: `"SteamCore AI" <${process.env.SMTP_USER}>`,
      to: process.env.COMPANY_EMAIL || process.env.SMTP_USER,
      subject: `New Lead: ${leadData.requirement} from ${leadData.fullName}`,
      html: adminHtml,
    };

    // Auto-Responder Email HTML for the User
    const userHtml = `
      <div style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e2e8f0; border-radius: 12px; overflow: hidden; background-color: #ffffff;">
        <div style="background-color: #ffffff; border-bottom: 2px solid #1F4E79; padding: 32px; text-align: center;">
          <img src="${process.env.FRONTEND_URL || 'https://steam-core.vercel.app'}/logo.png" alt="SteamCore" style="height: 70px; width: auto; margin-bottom: 12px;" />
          <p style="color: #64748b; margin: 0; font-size: 15px; font-weight: 500;">Energy Engineering LLP</p>
        </div>
        <div style="padding: 40px 32px;">
          <h2 style="color: #0f172a; margin-top: 0; font-size: 22px;">Hello ${leadData.fullName.split(' ')[0]},</h2>
          <p style="color: #475569; font-size: 16px; line-height: 1.6;">Thank you for chatting with our SteamCore AI Assistant! We have successfully received your inquiry regarding <strong>${leadData.requirement}</strong>.</p>
          <p style="color: #475569; font-size: 16px; line-height: 1.6;">Our Senior Engineering Consultant will review your details and reach out to you directly via ${leadData.preferredContactMethod || 'Email'} to assist you further.</p>
          
          <p style="color: #475569; font-size: 16px; line-height: 1.6; margin-top: 32px;">If you need immediate assistance in the meantime, feel free to call us at <strong>+91 88508 47485</strong>.</p>
          
          <p style="color: #0f172a; font-size: 16px; font-weight: 600; margin-top: 32px; margin-bottom: 0;">Best Regards,</p>
          <p style="color: #475569; font-size: 16px; margin-top: 4px;">The SteamCore Engineering Team</p>
        </div>
        <div style="background-color: #f1f5f9; padding: 24px; text-align: center; color: #64748b; font-size: 13px;">
          <p style="margin: 0;">F-103 Greenscape Royale, Plot 25, Sector 7, Raigad – 410209</p>
          <p style="margin: 8px 0 0 0;">&copy; ${new Date().getFullYear()} SteamCore Energy Engineering LLP. All rights reserved.</p>
        </div>
      </div>
    `;

    const userMailOptions = {
      from: `"SteamCore AI" <${process.env.SMTP_USER}>`,
      to: leadData.email,
      subject: `We've received your request - SteamCore AI`,
      html: userHtml
    };

    // Send both emails
    await transporter.sendMail(adminMailOptions);
    await transporter.sendMail(userMailOptions);
  } catch (error) {
    console.error('Error sending lead email:', error);
    // Don't fail the lead creation if email fails
  }
};

export const createLead = async (req, res) => {
  try {
    const lead = await Lead.create(req.body);
    
    // Attempt to send email notification
    if (process.env.SMTP_USER && process.env.COMPANY_EMAIL) {
      await sendLeadEmail(lead);
    }

    res.status(201).json({ success: true, data: lead });
  } catch (error) {
    res.status(500).json({ success: false, message: 'Server Error', error: error.message });
  }
};

export const getLeads = async (req, res) => {
  try {
    const leads = await Lead.find().sort({ createdAt: -1 });
    res.json({ success: true, data: leads });
  } catch (error) {
    res.status(500).json({ success: false, message: 'Server Error' });
  }
};

export const deleteLead = async (req, res) => {
  try {
    await Lead.findByIdAndDelete(req.params.id);
    res.json({ success: true, message: 'Lead deleted' });
  } catch (error) {
    res.status(500).json({ success: false, message: 'Server Error' });
  }
};
